### ISSUE TITLE
Move DbHelper class to use Room instead

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#709]
It's very long, with lot of different methods for various areas. Can this be split up into different functional areas (eg user/course/activity etc)?

**Comment by jjoseba** [comment]
Since last year, it is available de Room Persistence Library (https://developer.android.com/topic/libraries/architecture/room), a simple ORM for SQLite. I've heard a lot of good things about it. I can give it a try and see how complex would it be to refactor the DbHelper into this so we have a better structured and cleaner code for all the DB access part.

**Comment by alexlittle** [comment]
transferred to OPPIA-119
