### ISSUE TITLE
v6.8.0 does not send data to the server

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#813]
From email:
"I was not able to send activity/registration files to the server via the "Submit to Server" function. Across multiple devices, I received the error message: "Error connecting to server. Please check you have an active internet connection and try again". However, I confirmed that internet still worked on the device (I could even log in/out and download course media on Oppia). This seems very reminiscent of the bug a while back when Oppia Mobile would not recognize the internet connection when attempting to log-in. "

**Comment by jjoseba** [comment]
The problem is not app related but in the server. The problem appears in the LMH fork (where the email is optional in the registration form) when trying to submit an offline registered user that has not entered an email. Since the app was not attempting to automatically register offline users before, we were not encountering this error. 
The solution is in the server, to be able to configure some registration fields as optional (see https://github.com/DigitalCampus/django-oppia/issues/593)
